### PR TITLE
fix: inject negative embeddings correctly

### LINKED ISSUE #69: Possible issue when auto-injecting negative embeddings
So, I'm not exactly sure if this is a mistake on my part or not, but I've been trying to use negative embeddings in ArtBot and Lucid Creations, and they don't properly work on either of them with auto-injections. ArtBot always injects the embedding, while it's optional with Lucid Creations (so you can inject manually).

Base parameters for all generations:
Base prompt - `1girl, college student, black hair, long hair, glasses, upper body`
Model - `Anything Diffusion`
Resolution - `512x768`
Seed - `1234`
Steps - `30`
Guidance - `7.5`
Sampler - `k_dpmpp_2m`
Karras - `Enabled`
Clip skip - `1` (default)

1) With just those settings with no negative prompt whatsoever:
image Same generation on ArtBot - https://tinybots.net/artbot?i=h7twhJUM16o

2) Manually injecting [EasyNegative](https://civitai.com/models/7808) (Inject Embedding: `No`) with `(embedding:7808:1)` 
image You can clearly see that the image has become "better" as to normal anime art standards. Not possible to repeat in ArtBot as it always injects embeddings automatically.

3) Automatically injecting the same [EasyNegative](https://civitai.com/models/7808) (Inject Embedding: `Negative prompt`) without specifying anything in the negative prompt. image It seems like that in the case of an automatic injection to the negative prompt, the embedding still somehow ends up in the positive prompt, making the image worse. Same generation on ArtBot - https://tinybots.net/artbot?i=gFD6RSgyfWB

### PR DESCRIPTION
**Pull request by tazlin**
See #69 

also reworks test to confirm this behavior.

### CODE REVIEW

**Comment by db0** [comment]
All the expected images are the same which is not right.

**Comment by tazlin** [comment]
I have changed the tests to expect the same image on output. The purpose of this is to make sure the inject behavior is working in a predictable way.

**Comment by db0** [comment]
Ah I see. If you think it helps with noticing issues, sure, but normally the comparison of the images would be automated. The pedant in me wants to mention that you could avoid uploading 3 references by pointing them all the same image :D

**Comment by tazlin** [comment]
I can just as soon do that. All I really want separate are the test output images anyway. 

Although, I do think it would highlight the fact to a manual review that they are expected to be the same with the duplicate images (as in, on a test failure).

**Pull request merged**
