### PR TITLE
feat: img2img on Stable Cascade, update comfyui to `40e124c6`; fix: minor bug fixes

### PR DESCRIPTION
**Pull request by db0**
- Adds remix support for Stable Cascade
- Fixes comfyui compat for upcoming comfyui version
  - See commit notes for https://github.com/Haidra-Org/hordelib/pull/219/commits/3b5909e722b026fb9abb22a41475647486a818b8 
- allow adhoc lora downloads to run concurrently 
  - See https://github.com/Haidra-Org/hordelib/pull/219/commits/2f42d315d6835b17837ae6e2b73f27f6dc7349db

TODO:
- [ ] Add additional fields to sdk (https://github.com/Haidra-Org/horde-sdk/issues/165)

### CODE REVIEW

**Comment by tazlin** [comment]
Looks OK to me. Let me know when you want to merge/release. The current version is only being used by the batching/docker branch users of the beta right now.

**Comment by db0** [comment]
Ok I'm working on the horde and then the worker integration. I may need to push more changes so I'll leave it open until I have it working e2e

**Comment by db0** [comment]
> readding it to the path is almost entirely for the benefit of the third party nodes which need to be excised from hordelib at the earliest possible opportunity (along with the controlnet rework) and at that point the change in `config_path.py` can be reverted/removed.

How come we need to remove the third party nodes from hordelib btw?

**Comment by tazlin** [comment]
> > readding it to the path is almost entirely for the benefit of the third party nodes which need to be excised from hordelib at the earliest possible opportunity (along with the controlnet rework) and at that point the change in `config_path.py` can be reverted/removed.
> 
> How come we need to remove the third party nodes from hordelib btw?

They are horribly out of date and have substantial - and very hacky - changes made by jug/me which make the code incompatible with updating it easily. This is the same category of problems we had when we were patching the comfyui code - it creates a functional fork of the nodes which really should be installed as a library or used in way that doesn't require all sorts of changes made by us.

**Comment by tazlin** [comment]
In order to add the new control net support, we will have to resolve this issue one way or another.

**Comment by tazlin** [comment]
I'm going to release these changes shortly for the purposes of beta testing. The general-release version of the worker is pinned to an earlier minor version, so this won't impact any workers but the beta workers.

**Comment by db0** [comment]
OK with me

**Pull request merged**
