### PR TITLE
fix: attempt to reload the json on fail

### PR DESCRIPTION
**Pull request by db0**
Some defensive programming to deal with multiprocess.

For me it kept my worker stable.

### CODE REVIEW

**Comment by tazlin** [comment]
Just confirming - the local wheel you built would have been based on the current up-to-date history on main right now? Which is to say, you didn't rebase onto main immediately prior to opening this PR?

**Comment by db0** [comment]
I did do a git pull on main and then git merge main, but there was nothing to merge apparently.

**Comment by tazlin** [comment]
What I am getting at is that the current `main` on hordelib has a minor version bump (which the worker is not yet pinned to, and so is largely untested in the wild), so did you build the local testing version using those commits (and therefore you tested the other changes), or did you *just now* rebase when PRing?

**Comment by db0** [comment]
I made this branch a week ago, and the main branch has had no commit for 2 weeks, so I'm pretty sure I've been running on the latest main

**Comment by tazlin** [comment]
Ok awesome - thanks!

**Pull request merged**
